import { NextRequest, NextResponse } from 'next/server';
import { z } from 'zod';
import { UAParser } from 'ua-parser-js';
import {
  IngestionPayloadSchema,
  TelemetryEventPayload,
  AiEventPayload,
  MusicPlaybackPayload,
  SystemIntegrityPayload,
  AiTrajectoryPayload,
  FormSubmissionPayload,
  EasterEggCompletionPayload,
} from '@/lib/schemas';
import { ingestClickhouseClient, calculateAiCost, calculateHypotheticalCost } from '@/lib/services'; // Adjust path if needed

export const runtime = 'edge';

// Optimized Geolocation using Vercel Native Edge Headers
function getGeoFromHeaders(req: NextRequest): {
  country: string;
  city: string;
  lat?: string;
  lon?: string;
} {
  const countryCode = req.headers.get('x-vercel-ip-country') || 'Unknown';
  const city = req.headers.get('x-vercel-ip-city') || 'Unknown';
  const lat = req.headers.get('x-vercel-ip-latitude') || undefined;
  const lon = req.headers.get('x-vercel-ip-longitude') || undefined;

  return { country: countryCode, city, lat, lon };
}

export async function POST(req: NextRequest) {
  const startTime = performance.now();
  let payload: z.infer<typeof IngestionPayloadSchema>;
  // 1. Validate Secret Key
  const ingestionSecretKey = process.env.INGESTION_SECRET_KEY;
  const xSecretKey = req.headers.get('x-secret-key');
  if (!ingestionSecretKey || ingestionSecretKey !== xSecretKey) {
    return NextResponse.json(
      { message: 'Unauthorized: Invalid or missing secret key' },
      { status: 401 },
    );
  }
  // 2. Parse and Validate Request Body
  try {
    const body = await req.json();
    payload = IngestionPayloadSchema.parse(body);
  } catch (error) {
    console.error('Ingestion Payload Validation Error:', error);
    return NextResponse.json(
      { message: 'Bad Request: Invalid payload', errors: error },
      { status: 400 },
    );
  }
  // 3. Data Enrichment (Server-side)
  let ip =
    req.headers.get('x-forwarded-for')?.split(',').shift() || // Common for proxy like Vercel
    req.headers.get('x-real-ip') || // Another common proxy header
    null;
  if (!ip || ip === '::1' || ip === 'localhost') {
    ip = '127.0.0.1';
  } else if (ip.startsWith('::ffff:')) {
    ip = ip.substring(7);
  }
  const cleanIp = ip === '127.0.0.1' || ip === '::1' ? '127.0.0.1' : ip || '0.0.0.0';
  const userAgentString = req.headers.get('user-agent');
  const parser = new UAParser(userAgentString || '');
  const deviceType = parser.getDevice().type || 'desktop'; // 'mobile', 'tablet', 'wearable','embedded'
  const os = parser.getOS().name || 'Unknown';
  const browser = parser.getBrowser().name || 'Unknown';

  const { country, city, lat, lon } = getGeoFromHeaders(req);

  const enrichedData = {
    timestamp: new Date().toISOString().slice(0, 19).replace('T', ' '),
    ip_address: cleanIp,
    userAgent: userAgentString,
    device_type: deviceType,
    os: os,
    browser: browser,
    country: country,
    city: city,
    latitude: lat,
    longitude: lon,
    sessionId: payload.sessionId || 'anonymous', // Default to anonymous if not provided
    url: payload.url || req.nextUrl.href, // Default to current request URL if not provided
  };
  // 4. Insert into ClickHouse (Non-blocking)
  try {
    switch (payload.type) {
      case 'telemetry_event': {
        const telemetryPayload: TelemetryEventPayload = payload;
        await ingestClickhouseClient.insert({
          table: 'analytics.telemetry_events_buffer', // Insert into buffer table for efficienc
          values: [
            {
              ...enrichedData,
              event: telemetryPayload.event,
              data: telemetryPayload.data
                ? Object.fromEntries(Object.entries(telemetryPayload.data))
                : {},
              // ClickHouse UUID is generated by DEFAULT generateUUIDv4()
            },
          ],
          format: 'JSONEachRow',
        });
        break;
      }
      case 'ai_event': {
        const aiPayload: AiEventPayload = payload;
        // Calculate cost server-side if not provided (allows for centralized pricing)
        const computedCost =
          aiPayload.cost_usd ??
          calculateAiCost(aiPayload.model, aiPayload.input_tokens, aiPayload.output_tokens);

        // Calculate opportunity savings
        const hypotheticalCost = calculateHypotheticalCost(
          aiPayload.input_tokens,
          aiPayload.output_tokens,
        );
        const savings = Math.max(0, hypotheticalCost - computedCost);

        await ingestClickhouseClient.insert({
          table: 'analytics.ai_intelligence',
          values: [
            {
              ...enrichedData,
              trace_id: aiPayload.trace_id || `trace_${crypto.randomUUID().slice(0, 8)}`,
              agent_name: aiPayload.agent_name,
              model: aiPayload.model,
              input_tokens: aiPayload.input_tokens,
              output_tokens: aiPayload.output_tokens,
              cost_usd: computedCost,
              savings_usd: savings,
              latency_ms: aiPayload.latency_ms,
              form_type: aiPayload.form_type || null,
            },
          ],
          format: 'JSONEachRow',
        });
        break;
      }
      case 'music_playback': {
        const musicPayload: MusicPlaybackPayload = payload;
        await ingestClickhouseClient.insert({
          table: 'analytics.music_playback',
          values: [
            {
              ...enrichedData,
              track_id: musicPayload.track_id,
              track_title: musicPayload.track_title,
              artist_name: musicPayload.artist_name || null,
              genre: musicPayload.genre || null,
              completion_pct: musicPayload.completion_pct,
              is_download: musicPayload.is_download ? 1 : 0, // ClickHouse UInt8 for boolean
            },
          ],
          format: 'JSONEachRow',
        });
        break;
      }
      case 'system_integrity': {
        const integrityPayload: SystemIntegrityPayload = payload;
        await ingestClickhouseClient.insert({
          table: 'analytics.system_integrity',
          values: [
            {
              ...enrichedData,
              service: integrityPayload.service,
              status: integrityPayload.status,
              latency_ms: integrityPayload.latency_ms || 0,
              error_count: integrityPayload.error_count || 0,
              payload_size: integrityPayload.payload_size || 0,
              message: integrityPayload.message || null,
            },
          ],
          format: 'JSONEachRow',
        });
        break;
      }
      case 'ai_trajectory': {
        const trajectoryPayload: AiTrajectoryPayload = payload;

        // Merge observation into state if present (Schema workaround)
        const stateWithObservation = {
          ...trajectoryPayload.state,
          ...(trajectoryPayload.observation ? { observation: trajectoryPayload.observation } : {}),
        };

        await ingestClickhouseClient.insert({
          table: 'analytics.ai_trajectories',
          values: [
            {
              ...enrichedData,
              trajectory_id: trajectoryPayload.trajectory_id,
              step_index: trajectoryPayload.step_index,
              state: JSON.stringify(stateWithObservation),
              action: trajectoryPayload.action,
              reward: trajectoryPayload.reward,
              metadata: JSON.stringify(trajectoryPayload.metadata || {}),
            },
          ],
          format: 'JSONEachRow',
        });
        break;
      }

      case 'form_submission': {
        const formPayload: FormSubmissionPayload = payload;
        await ingestClickhouseClient.insert({
          table: 'analytics.form_submissions',
          values: [
            {
              ...enrichedData,
              form_type: formPayload.form_type,
              source: formPayload.source,
              intent: formPayload.intent || null,
              sentiment: formPayload.sentiment || null,
              summary: formPayload.summary || null,
              tags: formPayload.tags || null,
            },
          ],
          format: 'JSONEachRow',
        });
        break;
      }

      case 'easter_egg_completion': {
        const eggPayload: EasterEggCompletionPayload = payload;
        await ingestClickhouseClient.insert({
          table: 'analytics.easter_egg_completions',
          values: [
            {
              ...enrichedData,
              egg_id: eggPayload.egg_id,
              egg_name: eggPayload.egg_name,
              trigger_type: eggPayload.trigger_type,
              completion_time_ms: eggPayload.completion_time_ms || 0,
              attempt_count: eggPayload.attempt_count || 1,
              metadata: JSON.stringify(eggPayload.metadata || {}),
            },
          ],
          format: 'JSONEachRow',
        });
        break;
      }

      default:
        console.warn('Unknown event type received:', (payload as any).type);
        break;
    }

    // Emit event to WebSocket server (non-blocking)
    const WS_URL = process.env.WS_URL;
    const WS_SECRET = process.env.WS_INTERNAL_SECRET;
    if (!WS_URL || !WS_SECRET) {
      console.warn('[WS-Bridge] WS_URL or WS_INTERNAL_SECRET not configured — skipping broadcast');
      return NextResponse.json(
        { message: 'Event ingested successfully', type: payload.type },
        { status: 200 },
      );
    }

    // Construct meaningful data payload based on event type
    let broadcastData: any = {};
    if (payload.type === 'telemetry_event') {
      broadcastData = payload.data || {};
    } else if (payload.type === 'ai_trajectory') {
      broadcastData = {
        action: payload.action,
        reward: payload.reward,
        trajectory_id: payload.trajectory_id,
        step: payload.step_index,
      };
    } else if (payload.type === 'ai_event') {
      broadcastData = {
        agent: payload.agent_name,
        model: payload.model,
        tokens: payload.input_tokens + payload.output_tokens,
        latency: payload.latency_ms,
      };
    } else if (payload.type === 'system_integrity') {
      broadcastData = {
        service: payload.service,
        status: payload.status,
        message: payload.message,
      };
    }

    fetch(WS_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-internal-secret': WS_SECRET,
      },
      body: JSON.stringify({
        ...enrichedData,
        type: payload.type,
        event: payload.type === 'telemetry_event' ? payload.event : payload.type,
        data: broadcastData,
      }),
    }).catch(async (err) => {
      console.error('[WS-Bridge] Emission failed:', err.message);

      // SELF-REPORT: Log bridge failure to ClickHouse
      try {
        await ingestClickhouseClient.insert({
          table: 'analytics.system_integrity',
          values: [
            {
              ...enrichedData,
              service: 'websocket-bridge',
              status: 'DOWN',
              latency_ms: 0,
              error_count: 1,
              message: `Connection Failed: ${err.message}`,
            },
          ],
          format: 'JSONEachRow',
        });
      } catch (chError) {
        console.error('[WS-Bridge] Critical: Failed to self-report bridge failure:', chError);
      }
    });

    const endTime = performance.now();
    const durationMs = endTime - startTime;
    console.log(
      `[INGEST] Type: ${payload.type} | Event: ${payload.type === 'telemetry_event' ? payload.event : 'N/A'} | Latency: ${durationMs.toFixed(2)}ms`,
    );

    return NextResponse.json(
      { message: 'Event ingested successfully', type: payload.type },
      { status: 200 },
    );
  } catch (clickhouseError) {
    console.error('ClickHouse Insertion Error:', clickhouseError);
    return NextResponse.json(
      { message: 'Internal Server Error: Failed to ingest event' },
      { status: 500 },
    );
  }
}

// export async function GET(req: NextRequest) {
//     return NextResponse.json({ message: 'Test' }, {status: 200 });
// }
