export * from './about';
export * from './animations';
export * from './blog';
export * from './contact';
export * from './content';
export * from './date';
export * from './datetime';
export * from './device';
export * from './dom';
export * from './env';
export * from './experiences';
export * from './export';
export * from './function';
export * from './journey/index';
export * from './math';
export * from './number';
export * from './preloader';
export * from './projects';
// TEST 16: comment out shiki export to check if @shikijs/core has CJS/async-module patterns
// export * from './shiki';
export * from './strapi';
export * from './string';
export * from './tags';
export * from './text';
export * from './url';
export * from './visuals';
export * as _ from 'lodash-es';
