version: 2.1

orbs:
  node: circleci/node@6.1.0

jobs:
  validate:
    executor:
      name: node/default
      tag: "20.11.1"
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: pnpm
      - run:
          name: "Verify Commit Messages"
          command: |
            # Validate commits on the PR branch
            if [ -n "$CIRCLE_PR_NUMBER" ]; then
              npx commitlint --from=main --to=HEAD
            fi
      - run:
          name: "Verify Changesets"
          command: npx changeset status
      - run:
          name: "Lint & Format Check"
          command: pnpm turbo lint format

  test:
    executor:
      name: node/default
      tag: "20.11.1"
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: pnpm
      - run:
          name: "Turbo Type-Check & Build"
          command: pnpm turbo type-check build

workflows:
  quality_gate:
    jobs:
      - validate
      - test:
          requires:
            - validate
