"use client";

import * as React from "react";
import { ShieldCheck } from "@aazucena/icons";
import { AssistantOverlay, AssistantOverlaySection } from "./AssistantOverlay";

interface AssistantTransparencyOverlayProps {
  onClose: () => void;
}

export function AssistantTransparencyOverlay({
  onClose,
}: AssistantTransparencyOverlayProps) {
  return (
    <AssistantOverlay
      icon={<ShieldCheck size={40} className="text-secondary shrink-0" />}
      title="Transparency"
      subtitle="How this chat works."
      onClose={onClose}
      footer={
        <button
          onClick={onClose}
          className="bg-foreground text-background mt-4 w-full rounded-lg py-2 text-xs font-semibold transition-opacity hover:opacity-80"
        >
          Got it
        </button>
      }
    >
      <AssistantOverlaySection label="Powered By">
        <p className="text-xs leading-relaxed">
          This chat is powered by Claude AI by Anthropic. Responses are
          generated by a large language model and may not always be accurate.
        </p>
      </AssistantOverlaySection>

      <AssistantOverlaySection label="Your Data">
        <p className="text-xs leading-relaxed">
          Your messages are stored locally in your browser only. Nothing is sent
          to a database or third party beyond the AI model processing your
          request.
        </p>
      </AssistantOverlaySection>

      <AssistantOverlaySection label="Context Sharing">
        <p className="text-xs leading-relaxed">
          The current page you're viewing is shared with the model so Rin can
          give relevant answers. No personal information is collected or
          retained.
        </p>
      </AssistantOverlaySection>

      <AssistantOverlaySection label="What Rin Can Do">
        <p className="text-xs leading-relaxed">
          If you ask Rin to send a message to Aldrin, it can submit a contact
          form on your behalf. You'll see a confirmation in the chat before
          anything is sent. This is the only case where information leaves your
          browser.
        </p>
      </AssistantOverlaySection>

      <div className="border-border/50 border-t pt-3">
        <p className="text-muted-foreground text-xs italic">
          Rin exists to help you understand Aldrin's work. Nothing more.
        </p>
      </div>
    </AssistantOverlay>
  );
}
