import {
  Briefcase,
  ClockCircle,
  Code,
  FileText,
  User,
  Shield,
  Rss as RssNav,
  Map,
  GitBranch,
  Send,
  Terminal,
  Github,
  GitCircle,
  Database,
  Servers,
  Cloud,
  Globe,
  Link,
  Wifi,
  Layout,
  Wrench,
  CogFour,
  Zap,
  Rocket,
  ArrowRight,
  Music,
  Video,
  Users,
  CheckCircle,
  Mobile,
  Microchip,
  Headphones,
  Microphone,
} from '@mynaui/icons-react';
import {
  Astro,
  React,
  Tailwind,
  Vite,
  Rss,
  Brand,
  GitHub,
  LinkedIn,
  Twitter,
  Youtube,
  Instagram,
  Facebook,
  Tiktok,
  Discord,
  Twitch,
  Mastodon,
  Email,
  Download,
  Image,
  Vector,
  ScrollDown,
  Empty,
  AwardBadge,
  Viewports,
  Lightbulb,
  LightbulbSolid,
  Robot,
  RobotSolid,
  Bug,
  BugSolid,
  Gamepad,
  GamepadSolid,
  Window,
  WindowSolid,
  PaintBrush,
  PaintBrushSolid,
  Cube,
  CubeSolid,
  Webhook,
  WebhookSolid,
  Palette,
  PaletteSolid,
  WandMagic,
  WandMagicSolid,
  FloppyDisk,
  FloppyDiskSolid,
  Brush,
  BrushSolid,
  Eraser,
  EraserSolid,
  CompassDraft,
  CompassDraftSolid,
  EyeDropper,
  EyeDropperSolid,
  Fill,
  FillSolid,
  UploadCloud,
  UploadCloudSolid,
  GitFork,
  GitForkSolid,
  License,
  LicenseSolid,
  Braces,
  BracesSolid,
  Type,
  TypeSolid,
} from './custom/index';
import type { IconComponent } from '@aazucena/types';
/**
 * Maps icon name string to @mynaui/icons-react component
 * Also handles SVG strings from strapi-plugin-icons-field
 */
export function getIconComponent(iconName: string | null | undefined): IconComponent {
  // Handle null/undefined/empty icon names - return fallback
  if (!iconName || iconName.trim() === '') {
    return Code as IconComponent;
  }

  // Check if iconName is an SVG string (from strapi-plugin-icons-field)
  if (iconName.startsWith('<svg')) {
    return iconName;
  }

  // Map icon names to components
  const iconMap: Record<string, IconComponent> = {
    // Custom Icons
    Astro: Astro as IconComponent,
    React: React as IconComponent,
    Tailwind: Tailwind as IconComponent,
    Vite: Vite as IconComponent,
    Rss: Rss as IconComponent,
    BrandLogo: Brand as IconComponent,
    ScrollDown: ScrollDown as IconComponent,
    Empty: Empty as IconComponent,
    AwardBadge: AwardBadge as IconComponent,
    Download: Download as IconComponent,
    DownloadAlt: Download as IconComponent,
    Vector: Vector as IconComponent,
    Viewports: Viewports as IconComponent,
    Lightbulb: Lightbulb as IconComponent,
    LightbulbSolid: LightbulbSolid as IconComponent,
    Robot: Robot as IconComponent,
    RobotSolid: RobotSolid as IconComponent,
    Bug: Bug as IconComponent,
    BugSolid: BugSolid as IconComponent,
    Gamepad: Gamepad as IconComponent,
    GamepadSolid: GamepadSolid as IconComponent,
    Window: Window as IconComponent,
    WindowSolid: WindowSolid as IconComponent,
    PaintBrush: PaintBrush as IconComponent,
    PaintBrushSolid: PaintBrushSolid as IconComponent,
    Cube: Cube as IconComponent,
    CubeSolid: CubeSolid as IconComponent,
    Webhook: Webhook as IconComponent,
    WebhookSolid: WebhookSolid as IconComponent,
    Palette: Palette as IconComponent,
    PaletteSolid: PaletteSolid as IconComponent,
    WandMagic: WandMagic as IconComponent,
    WandMagicSolid: WandMagicSolid as IconComponent,
    FloppyDisk: FloppyDisk as IconComponent,
    FloppyDiskSolid: FloppyDiskSolid as IconComponent,
    Brush: Brush as IconComponent,
    BrushSolid: BrushSolid as IconComponent,
    Eraser: Eraser as IconComponent,
    EraserSolid: EraserSolid as IconComponent,
    CompassDraft: CompassDraft as IconComponent,
    CompassDraftSolid: CompassDraftSolid as IconComponent,
    EyeDropper: EyeDropper as IconComponent,
    EyeDropperSolid: EyeDropperSolid as IconComponent,
    Fill: Fill as IconComponent,
    FillSolid: FillSolid as IconComponent,
    UploadCloud: UploadCloud as IconComponent,
    UploadCloudSolid: UploadCloudSolid as IconComponent,
    GitFork: GitFork as IconComponent,
    GitForkSolid: GitForkSolid as IconComponent,
    License: License as IconComponent,
    LicenseSolid: LicenseSolid as IconComponent,
    Braces: Braces as IconComponent,
    BracesSolid: BracesSolid as IconComponent,
    Type: Type as IconComponent,
    TypeSolid: TypeSolid as IconComponent,

    // Official Social Logos
    GitHubAlt: GitHub as IconComponent,
    LinkedIn: LinkedIn as IconComponent,
    Twitter: Twitter as IconComponent,
    X: Twitter as IconComponent,
    YouTube: Youtube as IconComponent,
    Instagram: Instagram as IconComponent,
    Facebook: Facebook as IconComponent,
    TikTok: Tiktok as IconComponent,
    Discord: Discord as IconComponent,
    Twitch: Twitch as IconComponent,
    Mastodon: Mastodon as IconComponent,
    EmailAlt: Email as IconComponent,

    // Library Icons
    Code: Code as IconComponent,
    Terminal: Terminal as IconComponent,
    Github: Github as IconComponent,
    Git: GitCircle as IconComponent,
    Database: Database as IconComponent,
    Server: Servers as IconComponent,
    Cloud: Cloud as IconComponent,
    Globe: Globe as IconComponent,
    Link: Link as IconComponent,
    Wifi: Wifi as IconComponent,
    Layout: Layout as IconComponent,
    Wrench: Wrench as IconComponent,
    CogFour: CogFour as IconComponent,
    Settings: CogFour as IconComponent,
    Zap: Zap as IconComponent,
    Bolt: Zap as IconComponent,
    Rocket: Rocket as IconComponent,
    ArrowRight: ArrowRight as IconComponent,
    Image: Image as IconComponent,
    Music: Music as IconComponent,
    Video: Video as IconComponent,
    Users: Users as IconComponent,
    User: User as IconComponent,
    CheckCircle: CheckCircle as IconComponent,
    Shield: Shield as IconComponent,
    DeviceMobile: Mobile as IconComponent,
    Chip: Microchip as IconComponent,
    Headphones: Headphones as IconComponent,
    Microphone: Microphone as IconComponent,
  };

  return iconMap[iconName] || (Code as IconComponent);
}

/**
 * Checks if an icon name is valid and exists in the icon map
 */
export function isValidIconName(iconName: string): boolean {
  const customIcons = [
    'Astro',
    'React',
    'Tailwind',
    'Vite',
    'Rss',
    'BrandLogo',
    'ScrollDown',
    'Empty',
    'GitHub',
    'LinkedIn',
    'Twitter',
    'X',
    'YouTube',
    'Instagram',
    'Facebook',
    'TikTok',
    'Discord',
    'Twitch',
    'Mastodon',
    'Email',
    'Lightbulb',
    'LightbulbSolid',
    'Robot',
    'RobotSolid',
    'Bug',
    'BugSolid',
    'Gamepad',
    'GamepadSolid',
    'Window',
    'WindowSolid',
    'PaintBrush',
    'PaintBrushSolid',
    'Cube',
    'CubeSolid',
    'Webhook',
    'WebhookSolid',
    'Palette',
    'PaletteSolid',
    'WandMagic',
    'WandMagicSolid',
    'FloppyDisk',
    'FloppyDiskSolid',
    'Brush',
    'BrushSolid',
    'Eraser',
    'EraserSolid',
    'CompassDraft',
    'CompassDraftSolid',
    'EyeDropper',
    'EyeDropperSolid',
    'Fill',
    'FillSolid',
    'UploadCloud',
    'UploadCloudSolid',
    'GitFork',
    'GitForkSolid',
    'License',
    'LicenseSolid',
    'Braces',
    'BracesSolid',
    'Type',
    'TypeSolid',
  ];
  const libraryIcons = [
    'Code', 'Terminal', 'Github', 'Git', 'Database', 'Server', 'Cloud', 'Globe',
    'Link', 'Wifi', 'Layout', 'Wrench', 'CogFour', 'Settings', 'Zap', 'Bolt',
    'Rocket', 'ArrowRight', 'Image', 'Music', 'Video', 'Users', 'User',
    'CheckCircle', 'Shield', 'DeviceMobile', 'Chip', 'Headphones', 'Microphone',
    'Download', 'DownloadAlt',
  ];
  return libraryIcons.includes(iconName) || iconName.startsWith('<svg') || customIcons.includes(iconName);
}

/**
 * Navigation-specific icon mapping
 */
export const navigationIcons = {
  briefcase: Briefcase,
  'clock-circle': ClockCircle,
  code: Code,
  'file-text': FileText,
  user: User,
  shield: Shield,
  rss: RssNav,
  map: Map,
  'git-branch': GitBranch,
  send: Send,
};

/**
 * Get navigation icon component by name
 */
export function getNavigationIcon(iconName?: string) {
  if (!iconName) return null;
  return (
    (navigationIcons as unknown as Record<string, import('react').ElementType>)[iconName] || null
  );
}
