import type { Meta, StoryObj } from '@storybook/react';
import React from 'react';
import { ChatImage } from '@aazucena/ui';

const meta: Meta<typeof ChatImage> = {
  title: 'Components/Chat/ChatImage',
  component: ChatImage,
  parameters: {
    layout: 'centered',
  },
  tags: ['autodocs'],
  argTypes: {
    src: {
      control: 'text',
      description: 'The source URL of the image.',
      table: {
        category: 'Content',
        type: { summary: 'string' },
      },
    },
    alt: {
      control: 'text',
      description: 'Alternative text for the image.',
      table: {
        category: 'Content',
        type: { summary: 'string' },
      },
    },
    caption: {
      control: 'text',
      description: 'Optional caption to display below the image.',
      table: {
        category: 'Content',
        type: { summary: 'string' },
      },
    },
    width: {
      control: 'number',
      description: 'Max width of the image (for display, not intrinsic size).',
      table: {
        category: 'Appearance',
        type: { summary: 'number' },
        defaultValue: { summary: '400' },
      },
    },
    height: {
      control: 'number',
      description: 'Max height of the image (for display, not intrinsic size).',
      table: {
        category: 'Appearance',
        type: { summary: 'number' },
        defaultValue: { summary: '300' },
      },
    },
    enlargeable: {
      control: 'boolean',
      description: 'If true, clicking the image will open it in a larger dialog.',
      table: {
        category: 'Behavior',
        type: { summary: 'boolean' },
        defaultValue: { summary: 'true' },
      },
    },
    variant: {
      control: 'select',
      options: ['default', 'glass', 'cyber'],
      description: 'Visual variant of the image container.',
      table: {
        category: 'Appearance',
        type: { summary: "'default' | 'glass' | 'cyber'" },
        defaultValue: { summary: 'default' },
      },
    },
  },
};

export default meta;
type Story = StoryObj<typeof ChatImage>;

export const Default: Story = {
  args: {
    src: 'https://via.placeholder.com/400x300/F0F0F0/333333?text=ChatImage',
    alt: 'Placeholder Image',
    caption: 'This is a sample image generated by the AI.',
  },
};

export const CyberVariant: Story = {
  args: {
    src: 'https://via.placeholder.com/600x400/06B6D4/FFFFFF?text=Cyber+Image',
    alt: 'Cyber Variant Image',
    caption: 'A futuristic visualization.',
    variant: 'cyber',
    width: 600,
    height: 400,
  },
};

export const GlassVariant: Story = {
  args: {
    src: 'https://via.placeholder.com/300x200/CBD5E1/475569?text=Glass+Image',
    alt: 'Glass Variant Image',
    caption: 'A translucent rendering.',
    variant: 'glass',
    width: 300,
    height: 200,
  },
};

export const NotEnlargeable: Story = {
  args: {
    src: 'https://via.placeholder.com/200x150/FFC107/000000?text=Small+Image',
    alt: 'Small, Not Enlargeable Image',
    caption: 'This image cannot be enlarged.',
    enlargeable: false,
    width: 200,
    height: 150,
  },
};

export const NoCaption: Story = {
  args: {
    src: 'https://via.placeholder.com/500x250/8BC34A/FFFFFF?text=Image+Without+Caption',
    alt: 'Image Without Caption',
    width: 500,
    height: 250,
  },
};
