import type { Meta, StoryObj } from '@storybook/react-vite';
import { InputOTP, InputOTPGroup, InputOTPSlot, InputOTPSeparator } from '@aazucena/ui';
import { Shield, Zap, Activity, Globe } from '@aazucena/icons';
import { Badge, Button } from '@aazucena/ui';

/**
 * ## Engineering Standards
 * - **Pattern:** Specialized input primitive for One-Time Passwords built on `input-otp`.
 * - **UX:** Features a "fake caret" animation and automatic focus management across groups.
 * - **Accessibility:** Built with standard ARIA roles for password inputs and supports screen reader announcements for slot values.
 * - **Aesthetics:** Optimized for high-security authentication flows with support for separators and grouping.
 */
const meta = {
  title: 'Components/Primitives/InputOTP',
  component: InputOTP,
  subcomponents: {
    InputOTPGroup,
    InputOTPSlot,
    InputOTPSeparator,
  } as any,
  parameters: {
    layout: 'centered',
    docs: {
      description: {
        component:
          'A robust input component for one-time passwords and verification codes. Supports complex grouping and visual separation.',
      },
    },
  },
  tags: ['autodocs'],
  argTypes: {
    maxLength: {
      control: 'number',
      description: 'The maximum number of characters',
      table: { category: 'Behavior' },
    },
    disabled: {
      control: 'boolean',
      description: 'Prevents user interaction',
      table: { category: 'State' },
    },
  },
} satisfies Meta<typeof InputOTP>;

export default meta;
type Story = StoryObj<typeof meta>;

// --- STORIES ---

/**
 * Standard 6-digit verification code implementation with a center separator.
 */
export const Basic: Story = {
  args: {
    maxLength: 6,
  },
  render: (args) => (
    <InputOTP {...args}>
      <InputOTPGroup>
        <InputOTPSlot index={0} />
        <InputOTPSlot index={1} />
        <InputOTPSlot index={2} />
      </InputOTPGroup>
      <InputOTPSeparator />
      <InputOTPGroup>
        <InputOTPSlot index={3} />
        <InputOTPSlot index={4} />
        <InputOTPSlot index={5} />
      </InputOTPGroup>
    </InputOTP>
  ),
};

/**
 * Technical implementation showing a secure enclave verification sequence.
 */
export const SecureEnclave: Story = {
  args: {
    maxLength: 4,
  },
  render: (args) => (
    <div className="p-12 border border-cyan-500/20 bg-black rounded-[2rem] text-center space-y-8">
      <div className="flex flex-col items-center gap-3">
        <Shield size={32} className="text-cyan-500 animate-pulse" />
        <h3 className="font-mono text-xs text-cyan-500 uppercase tracking-[0.3em]">
          // AUTH_SEQUENCE_REQUIRED
        </h3>
      </div>

      <div className="flex justify-center">
        <InputOTP {...args}>
          <InputOTPGroup>
            <InputOTPSlot
              index={0}
              className="size-14 text-xl font-mono border-cyan-500/30 text-cyan-400 bg-cyan-500/5 rounded-xl mr-2"
            />
            <InputOTPSlot
              index={1}
              className="size-14 text-xl font-mono border-cyan-500/30 text-cyan-400 bg-cyan-500/5 rounded-xl mr-2"
            />
            <InputOTPSlot
              index={2}
              className="size-14 text-xl font-mono border-cyan-500/30 text-cyan-400 bg-cyan-500/5 rounded-xl mr-2"
            />
            <InputOTPSlot
              index={3}
              className="size-14 text-xl font-mono border-cyan-500/30 text-cyan-400 bg-cyan-500/5 rounded-xl"
            />
          </InputOTPGroup>
        </InputOTP>
      </div>

      <p className="text-[10px] font-mono text-cyan-500/40 uppercase">
        Enter the 4-digit token generated by your hardware key.
      </p>
    </div>
  ),
};

/**
 * Large format implementation for high-impact authentication screens.
 */
export const LargeFormat: Story = {
  args: {
    maxLength: 4,
  },
  render: (args) => (
    <div className="space-y-12 text-center">
      <h2 className="text-4xl font-black tracking-tighter uppercase">Identify_Self</h2>
      <InputOTP {...args}>
        <InputOTPGroup className="gap-4">
          <InputOTPSlot index={0} className="size-20 text-3xl rounded-2xl border-2" />
          <InputOTPSlot index={1} className="size-20 text-3xl rounded-2xl border-2" />
          <InputOTPSlot index={2} className="size-20 text-3xl rounded-2xl border-2" />
          <InputOTPSlot index={3} className="size-20 text-3xl rounded-2xl border-2" />
        </InputOTPGroup>
      </InputOTP>
      <Button
        variant="ghost"
        className="opacity-40 hover:opacity-100 uppercase tracking-widest text-[10px]"
      >
        Resend_Verification_Packet
      </Button>
    </div>
  ),
};

/**
 * Visual feedback when the input is in a disabled state.
 */
export const Disabled: Story = {
  args: {
    maxLength: 4,
    disabled: true,
  },
  render: (args) => (
    <div className="space-y-4 text-center">
      <Badge variant="destructive" size="xs">
        SYSTEM_LOCKED
      </Badge>
      <InputOTP {...args}>
        <InputOTPGroup>
          <InputOTPSlot index={0} />
          <InputOTPSlot index={1} />
          <InputOTPSlot index={2} />
          <InputOTPSlot index={3} />
        </InputOTPGroup>
      </InputOTP>
    </div>
  ),
};
