import type { SystemThemeConfig, ThemeVibe } from '@aazucena/types';
import { getColor } from '../tokens/colors';

const light: SystemThemeConfig = {
  colors: {
    primary: getColor('indigo', 500, 0.85),
    primaryForeground: getColor('zinc', 50),
    secondary: getColor('purple', 500, 0.85),
    secondaryForeground: getColor('zinc', 50),
    success: getColor('blue', 500, 0.85),
    successForeground: getColor('zinc', 50),
    destructive: getColor('red', 500, 0.85),
    destructiveForeground: getColor('zinc', 50),
    error: getColor('red', 500, 0.85),
    errorForeground: getColor('zinc', 50),
    background: getColor('blue', 50, 0.8),
    backgroundGradient: `linear-gradient(135deg, ${getColor('blue', 50, 0.8)} 0%, ${getColor('indigo', 50, 0.8)} 100%)`,
    base: getColor('blue', 50, 0.8),
    elevated: getColor('zinc', 50, 0.65),
    floating: getColor('zinc', 50, 0.85),
    cardBackground: getColor('zinc', 50, 0.6),
    overlayBackground: getColor('zinc', 50, 0.85),
    foreground: getColor('zinc', 900),
    mutedForeground: getColor('zinc', 500),
    accent: getColor('pink', 500, 0.85),
    accentForeground: getColor('zinc', 50),
    border: getColor('zinc', 900, 0.1),
  },
  effects: {
    backdropBlur: 'blur(24px)',
    cardBlur: 'blur(32px)',
    shadow: `0 8px 32px ${getColor('indigo', 200, 0.3)}`,
    glowColor: getColor('pink', 400, 0.35),
    borderRadius: {
      card: '1.5rem',
      button: '1rem',
      badge: '9999px',
      progress: '9999px',
    },
    animationSpeed: 1.1,
    animationEasing: 'cubic-bezier(0.4, 0, 0.2, 1)',
  },
  typography: {
    titleSize: '1.5rem',
    titleWeight: '600',
    subtitleSize: '0.875rem',
    headingFont: 'sans',
    bodyFont: 'sans',
  },
};

const dark: SystemThemeConfig = {
  colors: {
    primary: getColor('indigo', 500, 0.9),
    primaryForeground: getColor('zinc', 50),
    secondary: getColor('purple', 500, 0.9),
    secondaryForeground: getColor('zinc', 50),
    success: getColor('blue', 500, 0.9),
    successForeground: getColor('zinc', 50),
    destructive: getColor('red', 500, 0.9),
    destructiveForeground: getColor('zinc', 50),
    error: getColor('red', 500, 0.9),
    errorForeground: getColor('zinc', 50),
    background: getColor('zinc', 900, 0.95),
    backgroundGradient: `linear-gradient(135deg, ${getColor('zinc', 900, 0.95)} 0%, ${getColor('zinc', 800, 0.95)} 100%)`,
    base: getColor('zinc', 900, 0.95),
    elevated: getColor('zinc', 800, 0.7),
    floating: getColor('zinc', 950, 0.9),
    cardBackground: getColor('zinc', 800, 0.7),
    overlayBackground: getColor('zinc', 950, 0.9),
    foreground: getColor('zinc', 50),
    mutedForeground: getColor('zinc', 300),
    accent: getColor('pink', 500, 0.9),
    accentForeground: getColor('zinc', 50),
    border: getColor('zinc', 50, 0.15),
  },
  effects: {
    backdropBlur: 'blur(24px)',
    cardBlur: 'blur(32px)',
    shadow: `0 8px 32px ${getColor('zinc', 950, 0.15)}`,
    glowColor: getColor('pink', 500, 0.5),
    borderRadius: {
      card: '1.5rem',
      button: '1rem',
      badge: '9999px',
      progress: '9999px',
    },
    animationSpeed: 1.1,
    animationEasing: 'cubic-bezier(0.4, 0, 0.2, 1)',
  },
  typography: {
    titleSize: '1.5rem',
    titleWeight: '600',
    subtitleSize: '0.875rem',
    headingFont: 'sans',
    bodyFont: 'sans',
  },
};

export const glassVibe: ThemeVibe = {
  id: 'glass',
  name: 'Glass',
  type: 'standard',
  light,
  dark,
};
