import type { SystemThemeConfig, ThemeVibe } from '@aazucena/types';
import { getColor } from '../tokens/colors.js';

const light: SystemThemeConfig = {
  colors: {
    primary: getColor('orange', 600),
    primaryForeground: getColor('zinc', 50),
    secondary: getColor('purple', 800),
    secondaryForeground: getColor('zinc', 50),
    success: getColor('lime', 600),
    successForeground: getColor('zinc', 50),
    destructive: getColor('red', 600),
    destructiveForeground: getColor('zinc', 50),
    error: getColor('red', 600),
    errorForeground: getColor('zinc', 50),
    background: getColor('zinc', 50),
    base: getColor('zinc', 50),
    elevated: getColor('zinc', 50),
    floating: getColor('zinc', 50, 0.9),
    cardBackground: getColor('zinc', 50),
    overlayBackground: getColor('zinc', 50, 0.9),
    foreground: getColor('zinc', 950),
    mutedForeground: getColor('zinc', 500),
    accent: getColor('purple', 600),
    accentForeground: getColor('zinc', 50),
    border: getColor('zinc', 200),
  },
  effects: {
    backdropBlur: 'blur(4px)',
    shadow: `0 10px 15px -3px ${getColor('orange', 600, 0.1)}`,
    borderRadius: {
      card: '0px',
      button: '0px',
      badge: '4px',
      progress: '0px',
    },
    animationSpeed: 0.8,
    animationEasing: 'steps(4)',
  },
  typography: {
    titleSize: '1.5rem',
    titleWeight: '900',
    subtitleSize: '0.875rem',
    headingFont: 'mono',
    bodyFont: 'sans',
  },
};

const dark: SystemThemeConfig = {
  colors: {
    primary: getColor('orange', 500),
    primaryForeground: getColor('zinc', 950),
    secondary: getColor('purple', 500),
    secondaryForeground: getColor('zinc', 50),
    success: getColor('lime', 400),
    successForeground: getColor('zinc', 950),
    destructive: getColor('red', 500),
    destructiveForeground: getColor('zinc', 50),
    error: getColor('red', 500),
    errorForeground: getColor('zinc', 50),
    background: getColor('zinc', 950),
    base: getColor('zinc', 950),
    elevated: getColor('zinc', 900),
    floating: getColor('zinc', 950, 0.98),
    cardBackground: getColor('zinc', 900),
    overlayBackground: getColor('zinc', 950, 0.98),
    foreground: getColor('zinc', 50),
    mutedForeground: getColor('zinc', 400),
    accent: getColor('orange', 500),
    accentForeground: getColor('zinc', 950),
    border: getColor('purple', 500, 0.3),
  },
  effects: {
    backdropBlur: 'blur(16px)',
    shadow: `0 0 30px ${getColor('orange', 500, 0.2)}, 0 0 10px ${getColor('purple', 500, 0.2)}`,
    glowColor: getColor('orange', 500, 0.5),
    borderRadius: {
      card: '0px',
      button: '0px',
      badge: '4px',
      progress: '0px',
    },
    animationSpeed: 1.5,
    animationEasing: 'cubic-bezier(0.19, 1, 0.22, 1)',
  },
  typography: {
    titleSize: '1.75rem',
    titleWeight: '900',
    subtitleSize: '0.9375rem',
    headingFont: 'mono',
    bodyFont: 'sans',
  },
  customClass: 'spooky-glow',
};

export const halloweenVibe: ThemeVibe = {
  id: 'halloween',
  name: 'Halloween',
  type: 'holiday',
  light,
  dark,
};
