import { z } from 'zod';

// Base schema for common telemetry event properties
// Properties like timestamp, url, sessionId will be added on the server-side
// ip_address, country, userAgent, device_type, os, browser are also server-side enriched
const BaseEventSchema = z.object({
  // `id` is generated by ClickHouse
  // `timestamp` is generated by ClickHouse
  // `ip_address` is enriched server-side
  // `country` is enriched server-side
  // `userAgent` is enriched server-side
  // `device_type` is enriched server-side
  // `os` is enriched server-side
  // `browser` is enriched server-side
  sessionId: z.string().uuid().optional().describe('Unique ID for the user session, UUID format'),
  url: z.string().url().optional().describe('URL where the event occurred'),
});

// --- Telemetry Event (e.g., Page View, Interaction, Client Error, Performance Metric) ---
export const TelemetryEventPayloadSchema = BaseEventSchema.extend({
  type: z.literal('telemetry_event').describe('Discriminator for telemetry events'),
  event: z
    .enum([
      'PageView',
      'Interaction',
      'ClientError',
      'PerformanceMetric',
      'Heartbeat', // Useful for active session tracking
      'CustomEvent',
    ])
    .describe('Specific type of telemetry event'),
  data: z
    .record(z.string(), z.string())
    .optional()
    .describe('Flexible key-value pairs for event-specific data'),
});
export type TelemetryEventPayload = z.infer<typeof TelemetryEventPayloadSchema>;

// --- AI Event (for ai_intelligence table) ---
export const AiEventPayloadSchema = BaseEventSchema.extend({
  type: z.literal('ai_event').describe('Discriminator for AI intelligence events'),
  trace_id: z.string().optional().describe('LangSmith trace ID or similar'),
  agent_name: z.string().describe('Name of the LLM agent/chain'),
  model: z.string().describe('LLM model used'),
  input_tokens: z.number().int().min(0).describe('Number of input tokens'),
  output_tokens: z.number().int().min(0).describe('Number of output tokens'),
  cost_usd: z
    .number()
    .min(0)
    .optional()
    .describe('Estimated cost of the LLM call in USD (calculated server-side if omitted)'),
  latency_ms: z.number().int().min(0).describe('Latency of the LLM call in milliseconds'),
  form_type: z.string().optional().describe('Contextual form type if applicable'),
});
export type AiEventPayload = z.infer<typeof AiEventPayloadSchema>;

// --- Music Playback Event (for music_playback table) ---
export const MusicPlaybackPayloadSchema = BaseEventSchema.extend({
  type: z.literal('music_playback').describe('Discriminator for music playback events'),
  track_id: z.string().describe('Unique ID for the music track'),
  track_title: z.string().describe('Title of the music track'),
  artist_name: z.string().optional().describe('Artist of the track'),
  genre: z.string().optional().describe('Genre of the music track'),
  completion_pct: z.number().int().min(0).max(100).describe('Percentage of track played (0-100)'),
  is_download: z.boolean().describe('True if downloaded, false if streamed'),
});
export type MusicPlaybackPayload = z.infer<typeof MusicPlaybackPayloadSchema>;

// --- System Integrity Event (for system_integrity table) ---
export const SystemIntegrityPayloadSchema = BaseEventSchema.extend({
  type: z.literal('system_integrity').describe('Discriminator for system integrity events'),
  service: z
    .string()
    .describe(
      "Name of the service ('strapi-cms', 'portfolio-frontend','redis-cache', 'clickhouse')",
    ),
  status: z.enum(['UP', 'DOWN', 'DEGRADED', 'RESPONDING']).describe('Health status of the service'),
  latency_ms: z
    .number()
    .int()
    .min(0)
    .optional()
    .describe('Response time of health check in milliseconds'),
  error_count: z.number().int().min(0).optional().describe('Number of errors detected'),
  payload_size: z.number().int().min(0).optional().describe('Size of the response payload'),
  message: z.string().optional().describe('Associated health check message'),
});
export type SystemIntegrityPayload = z.infer<typeof SystemIntegrityPayloadSchema>;

// --- AI Trajectory Event (for ai_trajectories table) ---
export const AiTrajectoryPayloadSchema = BaseEventSchema.extend({
  type: z.literal('ai_trajectory').describe('Discriminator for AI RL trajectory events'),
  trajectory_id: z.string().describe('Unique ID for the full trajectory'),
  step_index: z.number().int().min(0).describe('Index of the step in the trajectory'),
  state: z.record(z.string(), z.any()).describe('JSON state of the agent'),
  observation: z.string().optional().describe('Rich observation data (JSON string)'),
  action: z.string().describe('Action taken by the agent'),
  reward: z.number().describe('Reward received for the action'),
  metadata: z.record(z.string(), z.any()).optional().describe('Flexible metadata for the step'),
});
export type AiTrajectoryPayload = z.infer<typeof AiTrajectoryPayloadSchema>;

// --- Form Submission Event (for form_submissions table) ---
export const FormSubmissionPayloadSchema = BaseEventSchema.extend({
  type: z.literal('form_submission').describe('Discriminator for form submission events'),
  form_type: z
    .enum(['contact_direct', 'contact_chatbot'])
    .describe('Which form triggered the submission'),
  source: z.enum(['direct_form', 'ai_assistant']).describe('Submission channel'),
  intent: z.string().optional().describe('AI-classified intent label'),
  sentiment: z
    .enum(['Very Positive', 'Positive', 'Neutral', 'Negative', 'Very Negative'])
    .optional()
    .describe('AI-classified visitor sentiment'),
  summary: z.string().optional().describe('AI one-sentence summary of the message'),
  tags: z.string().optional().describe('JSON-stringified tag array from AI classification'),
});
export type FormSubmissionPayload = z.infer<typeof FormSubmissionPayloadSchema>;

// --- Easter Egg Completion Event (for easter_egg_completions table) ---
export const EasterEggCompletionPayloadSchema = BaseEventSchema.extend({
  type: z.literal('easter_egg_completion').describe('Discriminator for easter egg events'),
  egg_id: z.string().describe('Unique identifier for the egg (e.g. "konami_code")'),
  egg_name: z.string().describe('Human-readable egg name'),
  trigger_type: z
    .enum(['konami', 'click_sequence', 'terminal_command', 'idle', 'cursor_pattern', 'rive'])
    .describe('Mechanism that triggered the egg'),
  completion_time_ms: z
    .number()
    .int()
    .min(0)
    .optional()
    .describe('Time from first interaction to completion in ms'),
  attempt_count: z.number().int().min(1).optional().describe('Number of attempts before success'),
  metadata: z
    .record(z.string(), z.any())
    .optional()
    .describe('Flexible extra data (sequence used, command typed, etc.)'),
});
export type EasterEggCompletionPayload = z.infer<typeof EasterEggCompletionPayloadSchema>;

// --- Main Ingestion Schema (Discriminated Union) ---
// This allows the /api/ingest endpoint to accept different payload shapes
// based on the 'type' field, routing them to the correct ClickHouse table.
export const IngestionPayloadSchema = z.discriminatedUnion('type', [
  TelemetryEventPayloadSchema,
  AiEventPayloadSchema,
  MusicPlaybackPayloadSchema,
  SystemIntegrityPayloadSchema,
  AiTrajectoryPayloadSchema,
  FormSubmissionPayloadSchema,
  EasterEggCompletionPayloadSchema,
]);
export type IngestionPayload = z.infer<typeof IngestionPayloadSchema>;
